### ISSUE TITLE
Build fails after go-plugins-helpers/volume was refactored

### ISSUE THREAD

**Issue by BioSLuDge** [projectatomic/docker-lvm-plugin#41]
Looks like 5 or 6 months ago go-plugins-helpers/volume was refactored and since then this project won't build

make
go-md2man -in man/docker-lvm-plugin.8.md -out docker-lvm-plugin.8
/usr/bin/go build -o docker-lvm-plugin .
_/home/andrew/docker-lvm-plugin
./driver.go:45: undefined: volume.Response
./driver.go:45: undefined: volume.Request
./driver.go:188: undefined: volume.Response
./driver.go:188: undefined: volume.Request
./driver.go:202: undefined: volume.Response
./driver.go:202: undefined: volume.Request
./driver.go:217: undefined: volume.Response
./driver.go:217: undefined: volume.Request
./driver.go:259: undefined: volume.Response
./driver.go:259: undefined: volume.Request
./driver.go:259: too many errors
Makefile:19: recipe for target 'lvm-plugin-build' failed
make: *** [lvm-plugin-build] Error 2

**Comment by maxhar** [comment]
facing the same problem

**Comment by 2Fast2BCn** [comment]
Same problem here? Any temporary workaround?

**Comment by rhatdan** [comment]
Could someone open a PR to fix this?
@shishir-a412ed Are you still interested in maintaining this?

**Comment by shishir-a412ed** [comment]
@rhatdan Yes, Let me take a look.

**Comment by shishir-a412ed** [comment]
@BioSLuDge @maxhar @2Fast2BCn I tried this on my Fedora VM, and I am able to `make` and build `docker-lvm-plugin` from source. I think something is messing up in your $GOPATH.

````
[smahajan@localhost docker-lvm-plugin]$ make
go-md2man -in man/docker-lvm-plugin.8.md -out docker-lvm-plugin.8
/usr/bin/go build -o docker-lvm-plugin .
[smahajan@localhost docker-lvm-plugin]$ sudo make install
install -D -m 644 etc/docker/docker-lvm-plugin /etc/docker/docker-lvm-plugin
install -D -m 644 systemd/docker-lvm-plugin.service /usr/lib/systemd/system/docker-lvm-plugin.service
install -D -m 644 systemd/docker-lvm-plugin.socket /usr/lib/systemd/system/docker-lvm-plugin.socket
install -D -m 755 docker-lvm-plugin /usr/libexec/docker/docker-lvm-plugin
install -D -m 644 docker-lvm-plugin.8 /usr/share/man/man8/docker-lvm-plugin.8
````

We use Godeps, and that's the whole point of using Godeps i.e. if upstream changes it's code it won't break our plugin since we use a specific version of `go-plugins-helpers/volume` 
https://github.com/projectatomic/docker-lvm-plugin/blob/master/Godeps/Godeps.json#L49-L50

Can you try this in a fresh golang environment and see if it fixes your problem:

1) mkdir -p $HOME/go/src/github.com
2) cd $HOME/go/src/github.com
3) export GOPATH=$HOME/go
4) git clone git@github.com:shishir-a412ed/docker-lvm-plugin.git
5) cd docker-lvm-plugin
6) make
7) sudo make install

**Comment by shishir-a412ed** [comment]
@BioSLuDge @maxhar @2Fast2BCn I have also updated the `docker-lvm-plugin` to work with latest version of `go-plugin-helpers` (Although it should work with the old version too).
Please see this: https://github.com/projectatomic/docker-lvm-plugin/pull/47
