### ISSUE TITLE
install path for docker-lvm-plugin config file

### ISSUE THREAD

**Issue by lsm5** [projectatomic/docker-lvm-plugin#5]
I think `/etc/sysconfig/docker-lvm-plugin` would be a good path for this as that's where other sysconfig files are located. Or should plugin configs go into `/etc/docker` ?

@shishir-a412ed @rhatdan @runcom wdyt?

**Comment by runcom** [comment]
see here https://github.com/shishir-a412ed/docker-lvm-plugin/issues/4

**Comment by runcom** [comment]
we basically didn't want `/etc/sysconfig` :)

**Comment by lsm5** [comment]
hmm ok

**Comment by rhatdan** [comment]
lokesh /etc/sysconfig is for altering the way that a service script runs,   /etc/FOOBAR.conf is for configuration of a service.  Docker is screwy since it does not have a configuration file, so we are abusing the /etc/sysconfig/docker* files to allow us to setup some kind of configuration data.  But we don't want to follow this for other services we support.

The systemd guys believe that /etc/sysconfig/* should be shot in the head...
